# Vaz's bash aliases

if [ "`uname`" = "Darwin" ]; then
    alias ls='ls -Gp'
    which wget >/dev/null 2>&1 || alias wget='curl -O'
    alias p='ps -eh -o pid,ppid,%cpu,%mem,command'
else
    alias ls='ls --color=auto -p'
    alias p='ps -eH --headers -o pid,%cpu,%mem,command'
fi

# ls
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -lha'

# screen
alias screen='screen -U'
alias sr='screen -r'

# working dir
alias cpwd="pwd | pbcopy"

# stuff
alias diditwork='test $? -eq 0 && echo yeah || echo nope'

# mud habits
alias grr='echo Grrrrr.'
alias yawn='echo You must be tired.'
alias yay='echo Yayyyy!'
alias fuck='echo FUCK.'
alias sigh='echo You sigh.'
alias hmm='echo Hmmm.'
alias lol='echo Hahaha.'
alias haha='echo Hahaha.'

alias ng='sudo /etc/init.d/nginx'

# work stuff
alias wdo='sudo -u www-data'

