# /Users/vaz/.rbenv/bin/rbenv init -
export PATH="/Users/vaz/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/Users/vaz/.rbenv/libexec/../completions/rbenv.bash'
rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "`rbenv "sh-$command" "$@"`";;
  *)
    command rbenv "$command" "$@";;
  esac
}
